#!/bin/bash

#check if gimp gtk3 folder exists and copy themes into config

if [ -d /usr/share/gimp/3.0/themes ]; then   
    cp -r /usr/share/themes/mx-ease/apps/gimp/mx-ease /usr/share/gimp/3.0/themes/mx-ease 
    cp -r /usr/share/themes/mx-ease-Dark/apps/gimp/mx-ease-Dark /usr/share/gimp/3.0/themes/mx-ease-Dark 
fi


# remove css from user home

name_of_login_user=$(logname)

if [ -d /home/$name_of_login_user/.config/GIMP/3.0/themes ]; then
    rm -rf /home/$name_of_login_user/.config/GIMP/3.0/themes/mx-ease
    rm -rf /home/$name_of_login_user/.config/GIMP/3.0/themes/mx-ease-Dark
fi
